version: 2.1

orbs:
  node: circleci/node@7.0.0

executors:
  node-executor:
    docker:
      - image: node:18  # Imagen base para Node.js

jobs:
  validations:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias Backend
          command: |
            cd Backend
            npm install
      - run:
          name: Instalar dependencias Frontend
          command: |
            cd Frontend
            npm install
      - run:
          name: Validación estática Backend
          command: |
            cd Backend
            npm install eslint
            npx eslint --fix
            npx eslint .
      - run:
          name: Validación estática Frontend
          command: |
            cd Frontend
            npm install eslint
            npx eslint .
      - run:
          name: Análisis de dependencias
          command: |
            cd Backend
            npm audit --production || true
            cd ../Frontend
            npm audit --production || true

  tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Ejecutar pruebas Backend
          command: |
            cd Backend
            npm install
            npm test

workflows:
  version: 2
  pipeline:
    jobs:
      - validations
      - tests
