version: 2.1

orbs:
  node: circleci/node@7.0.0

executors:
  node-executor:
    docker:
      - image: node:18  # Imagen base para Node.js
  docker-executor:
    docker:
      - image: cimg/base:stable  # Imagen base para Docker

jobs:
  pre_build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias Backend
          command: |
            cd Backend
            npm install
      - run:
          name: Instalar dependencias Frontend
          command: |
            cd Frontend
            npm install
      - run:
          name: Validación estática Backend
          command: |
            cd Backend
            npm install eslint
            npx eslint --fix
            npx eslint .
      - run:
          name: Validación estática Frontend
          command: |
            cd Frontend
            npm install eslint
            npx eslint .
      - run:
          name: Análisis de dependencias
          command: |
            cd Backend
            npm audit --production || true
            cd ../Frontend
            npm audit --production || true

  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Construir imágenes Docker
          environment:
            DOCKER_HOST: tcp://localhost:2375
          command: |
            docker build -t test/backend ./Backend
            docker build -t test/frontend ./Frontend

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Ejecutar pruebas Backend
          command: |
            cd Backend
            npm install
            npm test

  deploy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Desplegar contenedores
          environment:
            DOCKER_HOST: tcp://localhost:2375
          command: |
            docker run -d -p 3900:3900 --name backend test/backend
            docker run -d -p 8080:8080 --name frontend test/frontend

workflows:
  version: 2
  pipeline:
    jobs:
      - pre_build
      - build:
          requires:
            - pre_build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
            